### ISSUE TITLE
Couldn't creating wheel

### ISSUE THREAD

**Issue by eelalzep** [bigcat88/pillow_heif#310] opened 2024-11-10 18:38 UTC
**Failed building wheel for pi-heif**

Building wheels for collected packages: pi-heif
  Building wheel for pi-heif (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pi-heif (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/AvifImagePlugin.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/HeifImagePlugin.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/__init__.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/_deffered_error.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/_lib_info.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/_version.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/as_plugin.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/constants.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/heif.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/misc.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      copying pi_heif/options.py -> build/lib.linux-aarch64-cpython-312/pi_heif
      running build_ext
      Looking for `libheif` using pkg-config.
      Checking for include file 'heif.h' in '/data/data/com.termux/files/usr/include'
      Checking for include file 'heif.h' in '/data/data/com.termux/files/usr/include/libheif'
      Found 'heif.h' in '/data/data/com.termux/files/usr/include/libheif'
      building '_pi_heif' extension
      creating build/temp.linux-aarch64-cpython-312/pi_heif
      aarch64-linux-android-clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/python3.12 -c pi_heif/_pi_heif.c -o build/temp.linux-aarch64-cpython-312/pi_heif/_pi_heif.o -Ofast -Werror
      aarch64-linux-android-clang: error: argument '-Ofast' is deprecated; use '-O3 -ffast-math' for the same behavior, or '-O3' to enable only conforming optimizations [-Werror,-Wdeprecated-ofast]
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pi-heif
Failed to build pi-heif
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pi-heif)

**Comment by bigcat88** [comment] 2024-11-10 19:34
duplicate of https://github.com/bigcat88/pillow_heif/issues/304

new release with fix will be no sooner than in two weeks

**Comment by ssnadra** [comment] 2024-11-23 13:28
any updates?

**Comment by bigcat88** [comment] 2024-11-23 16:33
Since a new libheif version was released at the same time, and it is quite cool, it was decided to release it with the new libheif version right away.

A critical bug was found in version 1.19.3, tests in this repo did not pass - I reported this to the libheif author.

Then another bug was found in version 1.19.4, the same -> a new issue was created in the libheif repo -> release of libheif version 1.19.5

Now we are waiting for the libheif version to be updated to 1.19.5 in `ppa:strukturag/libheif` - another person is responsible for this, when he has time, he will update it.

As soon as this happens (I hope within 7 days) - the CI here will turn green, and I will need 1-2 days to prepare everything for the release and it will be released.

**Comment by jramiroz98** [comment] 2024-11-26 20:42
Let me know when its fixed, running into the same issue here

**Comment by bigcat88** [comment] 2024-11-29 10:08
should be fixed in the new release

**Comment by eelalzep** [comment] 2024-11-30 16:17
> should be fixed in the new release

No errors from pi-heif but lxml is stuck!!😭

**Comment by bigcat88** [comment] 2024-12-11 08:48
You can skip installing  `lxml`, I think.

I'll close this issue as resolved, if you do not mind.

**Closed by bigcat88** 2024-12-11 08:48 UTC
